from .nodes.ComfyUI_LLM_openai.llm_openai_nodes import (
    NODE_CLASS_MAPPINGS as LLM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LLM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.ComfyUI_Annotator_Preprocess.controlnet_preprocess import (
    NODE_CLASS_MAPPINGS as CTRL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CTRL_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.Image_Compare.image_compare import (
    NODE_CLASS_MAPPINGS as CMP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CMP_NODE_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LLM_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CTRL_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CMP_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LLM_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CTRL_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CMP_NODE_DISPLAY_NAME_MAPPINGS)

try:
    from .nodes.ComfyUI_LLM_openai import comfyui_llm_openai_server as _server  # noqa: F401
except Exception:
    pass
